# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Councilmember Rigel Robinson | City of Berkeley
email: rrobinson@cityofberkeley.info
phone: +1 (510) 981-7170
description: >- # this means to ignore newlines until "baseurl:"
    Councilmember Rigel Robinson has big plans for the City of Berkeley
url: ""
# twitter_username:  
logo: "/assets/img/logo.png"

address:
  - Office of Berkeley City Councilmember Rigel Robinson
  - 2180 Milvia Street, 5th Floor
  - Berkeley, CA 94704
  - United States

boxlinks:
  -
    - label: Legislation
      link: "/legislation"
      img: "/assets/img/rigel-podium.png"
  -
    - label: City Resources
      link: "/city-services"
      img: "/assets/img/kids.png"
    - label: Contact Us
      link: "/contact"
      img: "/assets/img/interns.png"

header_pages:
  - "about.md"
  - "district7.md"
  - "legislation.md"
  - "newsroom.md"
  - "city-services.md"
  - "get-involved.md"
  - "contact.md"

facebook_username: CouncilmemberRigelRobinson
twitter_username: RigelRobinson
instagram_username: RigelRobinson

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  - staff
  - legislation
  - resolutions

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
